### ISSUE TITLE
Event Mapping in Meteor does not work

### ISSUE THREAD

**Issue by dennismonsewicz** [amrali/bootstrap-select-meteor#2]
I am using bootstrap-select in an app I am building but when I write my event map out to alert me on a change event, nothing happens.

```
Template.selector.events({
  'change select': function(event) {
    alert("OUCH!");
  }
});
```

**Comment by amrali** [comment]
It seems Meteor doesn't support custom events which bootstrap-select relies on. This has been a problem for me. Use jQuery instead.

**Comment by dennismonsewicz** [comment]
Yeah, I ended up having to map the event down the chain to the <a> tag that
is generated by the plugin.

On Sunday, March 23, 2014, Amr Ali notifications@github.com wrote:

> It seems Meteor doesn't support custom events which bootstrap-select
> relies on. This has been a problem for me. Use jQuery instead.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/amrali/bootstrap-select-meteor/issues/2#issuecomment-38384559
> .

## 

Dennis Monsewicz Jr.
C: (256) 339-8716
dennismonsewicz.com

**Comment by amrali** [comment]
Ah.. good to know. Thanks.

**Comment by dennismonsewicz** [comment]
Here is what it looks like:

```
Template.selector.events({
  'click div.select-block ul.dropdown-menu li': function(e) {
     .... do things on click ....
  }
});
```

**Comment by udondan** [comment]
Looks like that has changed with Blaze.

I have no problems with this:

``` JS
Template.selector.events({
  'change select': handler
});
```
